In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

## Link to main toutorial by Pietro Marchesi
https://pietromarchesi.net/pca-neural-data.html#example

In [22]:
mouse = 'reach1_4'

In [23]:
if mouse == 'necab1':
    num_reaches = 182

if mouse == 'reach1_4':
    num_reaches = 278

probe = 'B' # probe used for the neural data
bin_size_in_ms = 50 # in milliseconds
output_dimension = 8 # number of dimensions for the embeddingspre
pre_reach = 0.5
post_reach = 10

In [24]:
pre_reach_str = str(pre_reach)
if pre_reach < 1:
    window_size = f'{pre_reach_str[0]}{pre_reach_str[-1]}_{post_reach}_timeWindow'
if pre_reach >= 1:
    window_size = f'{pre_reach_str}_{post_reach}_timeWindow'

In [20]:
# the path to the .npy file for the neural data (structred as firing rates x time x neurons)
neural_data_path =f'neural_data/{mouse}_{bin_size_in_ms}ms_FR_{window_size}_{probe}.npy'
print(neural_data_path)
neural_data = np.load(neural_data_path)
neural_data.shape, neural_data[0:2].shape

neural_data/reach1_4_50ms_FR_05_10_timeWindow_B.npy


((538, 58380), (2, 58380))

### Example cell 1

In [18]:
def center(X):
    # X: ndarray, shape (n_features, n_samples)
    ss = StandardScaler(with_mean=True, with_std=False)
    Xc = ss.fit_transform(X.T).T
    return Xc

X = np.array([[5., 6., 5.],
              [50., 60., 50.]]) # data array of shape n_neuron by n_time_points
print(X.shape)

X = center(X)
c = np.cov(X, rowvar=True) # covariance matrix
eig_vals, eig_vecs = np.linalg.eig(c)
srt = np.argsort(eig_vals)[::-1]

print('Sorted eigenvalues: \n{}'.format(eig_vals[srt]))
print('\nFirst eigenvector: \n{}'.format(eig_vecs[:, srt][:, 0]))

(2, 3)
Sorted eigenvalues: 
[33.66666667  0.        ]

First eigenvector: 
[-0.09950372 -0.99503719]


### My cell 1

In [33]:
def center(X):
    # X: ndarray, shape (n_features, n_samples)
    ss = StandardScaler(with_mean=True, with_std=False)
    Xc = ss.fit_transform(X.T).T
    return Xc

# replaced X with my neural data
X = neural_data  # data array of shape n_neuron by n_time_points
print(X.shape)

X = center(X)
c = np.cov(X, rowvar=True) # covariance matrix
eig_vals, eig_vecs = np.linalg.eig(c)
srt = np.argsort(eig_vals)[::-1]
print(eig_vecs.shape)
print('Sorted eigenvalues: \n{}'.format(eig_vals[srt][0:5]))
print('\nFirst eigenvector: \n{}'.format(eig_vecs[:, srt][:, 0]))

(538, 58380)
(538, 538)
Sorted eigenvalues: 
[6509.96994074 3669.76572868 1985.66545791 1477.82333342 1210.21058189]

First eigenvector: 
[-4.67649671e-02 -6.59118091e-02 -2.71503536e-04 -1.95370560e-02
 -2.54387349e-02 -1.28248341e-03  7.20004516e-04 -7.30451968e-02
 -1.11118244e-03 -1.23658508e-01 -3.30815679e-03 -8.40623034e-06
  8.08810057e-03 -2.80368078e-04 -3.55216648e-02 -1.94234555e-02
 -3.07528163e-03 -2.42920265e-04 -5.28665467e-04 -1.33516554e-02
 -3.38228341e-02 -5.98593426e-02 -3.67048167e-04 -5.13661587e-02
 -6.44330562e-02 -5.25812700e-03 -2.19638959e-02 -9.09077571e-02
 -1.74350659e-03 -1.22388959e-02 -6.11684234e-02 -9.34106874e-03
 -1.28325428e-02 -2.62349487e-05  4.99987142e-04 -1.24274440e-03
 -3.73832790e-04 -2.32175698e-02  3.89920335e-04 -6.21502722e-02
 -8.10518070e-04 -4.51886825e-02 -3.30270074e-02 -6.58601725e-02
 -1.04533217e-01 -4.31250442e-02 -1.61804174e-04  2.39276145e-05
 -9.80000609e-02 -1.94782925e-05 -5.14828382e-03 -5.16252910e-02
 -1.82521439e-02 

In [37]:
# Apply centering
neural_data_centered = center(neural_data)
neural_data_centered[5][0:20], neural_data[5][0:20]

(array([19.3096951, -0.6903049, -0.6903049, 19.3096951, 19.3096951,
        -0.6903049, 19.3096951, 19.3096951, 39.3096951, 39.3096951,
        59.3096951, 19.3096951, 39.3096951, -0.6903049, -0.6903049,
        -0.6903049, -0.6903049, 19.3096951, 19.3096951, -0.6903049]),
 array([20.,  0.,  0., 20., 20.,  0., 20., 20., 40., 40., 60., 20., 40.,
         0.,  0.,  0.,  0., 20., 20.,  0.]))

In [35]:
def center(X):
    # X: ndarray, shape (n_features, n_samples)
    ss = StandardScaler(with_mean=True, with_std=False)
    Xc = ss.fit_transform(X.T).T
    return Xc

# replaced X with my neural data
X = neural_data_centered  # data array of shape n_neuron by n_time_points
print(X.shape)

X = center(X)
c = np.cov(X, rowvar=True) # covariance matrix
eig_vals, eig_vecs = np.linalg.eig(c)
srt = np.argsort(eig_vals)[::-1]
print(eig_vecs.shape)
print('Sorted eigenvalues: \n{}'.format(eig_vals[srt][0:5]))
print('\nFirst eigenvector: \n{}'.format(eig_vecs[:, srt][:, 0]))

(538, 58380)
(538, 538)
Sorted eigenvalues: 
[6509.96994074 3669.76572868 1985.66545791 1477.82333342 1210.21058189]

First eigenvector: 
[-4.67649671e-02 -6.59118091e-02 -2.71503536e-04 -1.95370560e-02
 -2.54387349e-02 -1.28248341e-03  7.20004516e-04 -7.30451968e-02
 -1.11118244e-03 -1.23658508e-01 -3.30815679e-03 -8.40623034e-06
  8.08810057e-03 -2.80368078e-04 -3.55216648e-02 -1.94234555e-02
 -3.07528163e-03 -2.42920265e-04 -5.28665467e-04 -1.33516554e-02
 -3.38228341e-02 -5.98593426e-02 -3.67048167e-04 -5.13661587e-02
 -6.44330562e-02 -5.25812700e-03 -2.19638959e-02 -9.09077571e-02
 -1.74350659e-03 -1.22388959e-02 -6.11684234e-02 -9.34106874e-03
 -1.28325428e-02 -2.62349487e-05  4.99987142e-04 -1.24274440e-03
 -3.73832790e-04 -2.32175698e-02  3.89920335e-04 -6.21502722e-02
 -8.10518070e-04 -4.51886825e-02 -3.30270074e-02 -6.58601725e-02
 -1.04533217e-01 -4.31250442e-02 -1.61804174e-04  2.39276145e-05
 -9.80000609e-02 -1.94782925e-05 -5.14828382e-03 -5.16252910e-02
 -1.82521439e-02 

In [40]:
original_means = np.mean(neural_data, axis=1)
centered_means = np.mean(neural_data_centered, axis=1)
print("Original Means:", original_means[0:5])
print("Centered Means:", centered_means[0:5])


Original Means: [13.74340528 18.59335389  0.35080507  4.16923604 21.2672148 ]
Centered Means: [-8.41259231e-16 -1.83051777e-15 -1.40209872e-16 -4.40103209e-16
  2.04083258e-15]
